name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      TELNYX_MOCK_VERSION: 0.8.10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: setup-telnyx-mock
        run: source ./.github/scripts/before_install.sh
      - name: Restore dependencies
        run: dotnet restore ./src/Telnyx.net.sln
      - name: Build
        run: dotnet build ./src/Telnyx.net.sln /clp:ErrorsOnly
      - name: Test
        run: dotnet test ./src/TelnyxTests/TelnyxTests.csproj --configuration Release /clp:ErrorsOnly
